name: 'Confluence'
description: 'Script to add file to page'
inputs:
  user_id:
    description: 'Attlasian user ID'
    required: true
  api_token: 
    description: 'Attlasian API token, SHOULD BE FROM SECRETS'
    required: true
  url:  
    description: 'The url of the confleunce instance'
    required: true
  space:  
    description: 'The Confluence space ID'
    required: true
  page_id:  
    description: 'The confleunce page to which you will attach the new child page'
    required: true
  heading:  
    description: 'Title for file / Image'
    required: true
  file-folder:  
    description: 'Location of file'
    required: true    
  file-name:  
    description: 'File name'
    required: true    
  file-type:  
    description: 'File type, "image" or anything esle'
    required: true    
    
runs:
  using: "composite"
  steps:
    - name : Confluence
      run: |
        chmod 700 ${{ github.action_path }}/add_file.sh
        sh ${{ github.action_path }}/add_file.sh "${{ inputs.user_id }}" "${{ inputs.api_token }}" "${{ inputs.url }}"  "${{ inputs.space }}" "${{ inputs.page_id }}" "${{ inputs.heading }}" "${{ inputs.file-folder }}" "${{ inputs.file-name }}" "${{ inputs.file-type }}"
      shell: bash
