name: 'Confluence'
description: 'Script to append to page'
inputs:
  user_id:
    description: 'Attlasian user ID'
    required: true
  api_token: 
    description: 'Attlasian API token, SHOULD BE FROM SECRETS'
    required: true
  url:  
    description: 'The url of the confleunce instance'
    required: true
  space:  
    description: 'The Confluence space ID'
    required: true
  page_id:  
    description: 'The confleunce page to which you will attach the new child page'
    required: true
  content:  
    description: 'Intitial content into page'
    required: true    
    default: 'Default page content'
    
runs:
  using: "composite"
  steps:
    - name : Confluence
      run: |
        chmod 700 ${{ github.action_path }}/append_page.sh
        sh ${{ github.action_path }}/append_page.sh "${{ inputs.user_id }}" "${{ inputs.api_token }}" "${{ inputs.url }}"  "${{ inputs.space }}" "${{ inputs.page_id }}" "${{ inputs.content }}"
      shell: bash

